-- MyBook bootstrap schema SQL. Database structure only.
-- Generated by MyBook; keep this file in sync with database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `accounts` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `desc` varchar(255) NOT NULL DEFAULT '',
  `relativeBalance` tinyint(1) NOT NULL DEFAULT '1',
  `isCredit` tinyint(1) NOT NULL DEFAULT '0',
  `usage` enum('Life','Investment','Transit','Unknown') NOT NULL DEFAULT 'Life',
  `_primaryAccount_Id` int DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_Accounts_name` (`name`),
  KEY `idx_Accounts_primaryAccount` (`_primaryAccount_Id`),
  CONSTRAINT `fk_Accounts_primaryAccount` FOREIGN KEY (`_primaryAccount_Id`) REFERENCES `accounts` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `accountinternalids` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `cardNo` varchar(128) NOT NULL DEFAULT '',
  `desc` varchar(255) NOT NULL DEFAULT '',
  `currencyType` enum('RMB','USD','JPY','SGD','HKD') DEFAULT NULL,
  `_account_Id` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_AccountInternalIds_account_card_no` (`_account_Id`,`cardNo`),
  CONSTRAINT `fk_AccountInternalIds_account` FOREIGN KEY (`_account_Id`) REFERENCES `accounts` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `finance` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NOT NULL DEFAULT '',
  `holdingType` enum('NASDAQ','ARCA','UST','SHANGHAI','CNFUND','Cash','Accrued') NOT NULL DEFAULT 'NASDAQ',
  `currentPriceTime` bigint NOT NULL DEFAULT '0',
  `_currentPrice_v` decimal(30,18) NOT NULL DEFAULT '0.000000000000000000',
  `_currentPrice_t` enum('RMB','USD','JPY','SGD','HKD') NOT NULL DEFAULT 'RMB',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_Finance_code_holding_type` (`code`,`holdingType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `statementimports` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `provider` enum('IBKRReportMail','ICBCBillMail','ICBCHistoryDetailMail','WiseMail','OCBCMail','OCBCStatementMail','NexusDpMonthlyReport','PayPalMail','Manual') NOT NULL DEFAULT 'Manual',
  `time` datetime(6) NOT NULL,
  `statementKey` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_StatementImports_provider_time_key` (`provider`,`time`,`statementKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `holdings` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NOT NULL DEFAULT '',
  `quantity` int NOT NULL DEFAULT '0',
  `_currentPrice_v` decimal(30,18) NOT NULL DEFAULT '0.000000000000000000',
  `desc` varchar(255) NOT NULL DEFAULT '',
  `_account_Id` int NOT NULL DEFAULT '0',
  `holdingType` enum('NASDAQ','ARCA','UST','SHANGHAI','CNFUND','Cash','Accrued') NOT NULL DEFAULT 'NASDAQ',
  `_currentPrice_t` enum('RMB','USD','JPY','SGD','HKD') NOT NULL DEFAULT 'RMB',
  `displayText` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_Holdings_account_code_holding_type` (`_account_Id`,`code`,`holdingType`),
  CONSTRAINT `fk_Holdings_account` FOREIGN KEY (`_account_Id`) REFERENCES `accounts` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `records` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `DestAccount` varchar(255) NOT NULL DEFAULT '',
  `isInternal` tinyint(1) NOT NULL DEFAULT '0',
  `matchedRecordId` int DEFAULT NULL,
  `matchedRecordReason` varchar(1024) NOT NULL DEFAULT '',
  `isRefundMatched` tinyint(1) NOT NULL DEFAULT '0',
  `date` datetime NOT NULL,
  `updateTime` datetime NOT NULL,
  `Source` varchar(1024) NOT NULL DEFAULT '',
  `Reason` varchar(1024) NOT NULL DEFAULT '',
  `_account_Id` int NOT NULL DEFAULT '0',
  `_descCurrency_v` decimal(30,18) DEFAULT NULL,
  `_descCurrency_t` enum('RMB','USD','JPY','SGD','HKD') DEFAULT NULL,
  `_Currency_v` decimal(30,18) NOT NULL DEFAULT '0.000000000000000000',
  `_Currency_t` enum('RMB','USD','JPY','SGD','HKD') NOT NULL DEFAULT 'RMB',
  `_statementImport_Id` int NOT NULL DEFAULT '0',
  `HoldingQuantity` int NOT NULL DEFAULT '0',
  `backup` json DEFAULT NULL,
  `postingDate` datetime(6) DEFAULT NULL,
  `_holding_Id` int NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `idx_Records_account` (`_account_Id`),
  KEY `idx_Records_statementImport` (`_statementImport_Id`),
  KEY `index_Records_balance_rollup` (`_account_Id`,`_Currency_t`,`_statementImport_Id`,`date`),
  KEY `index_Records_import_date` (`_statementImport_Id`,`date`,`_account_Id`,`_Currency_t`),
  KEY `fk_Records_matchedRecord` (`matchedRecordId`),
  KEY `fk_Records_holding` (`_holding_Id`),
  CONSTRAINT `fk_Records_account` FOREIGN KEY (`_account_Id`) REFERENCES `accounts` (`Id`),
  CONSTRAINT `fk_Records_holding` FOREIGN KEY (`_holding_Id`) REFERENCES `holdings` (`Id`),
  CONSTRAINT `fk_Records_matchedRecord` FOREIGN KEY (`matchedRecordId`) REFERENCES `records` (`Id`),
  CONSTRAINT `fk_Records_statementImport` FOREIGN KEY (`_statementImport_Id`) REFERENCES `statementimports` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `snapshots` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `source` enum('AutoDaily','Manual','Start') NOT NULL DEFAULT 'AutoDaily',
  `time` datetime(6) NOT NULL,
  `schemaVersion` int NOT NULL DEFAULT '1',
  `snapshotKey` varchar(128) NOT NULL DEFAULT '',
  `createdAt` datetime(6) NOT NULL,
  `maxStatementImportId` int NOT NULL DEFAULT '-1',
  `effectiveDate` date NOT NULL DEFAULT '1000-01-01',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_Snapshots_source_key` (`source`,`snapshotKey`),
  KEY `index_Snapshots_effective_revision` (`effectiveDate`,`maxStatementImportId`),
  KEY `index_Snapshots_revision` (`maxStatementImportId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `snapshotitems` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `itemType` enum('AccountBalance','Holding') NOT NULL DEFAULT 'AccountBalance',
  `stableKey` varchar(256) NOT NULL DEFAULT '',
  `accountName` varchar(256) NOT NULL DEFAULT '',
  `currencyType` enum('RMB','USD','JPY','SGD','HKD') DEFAULT NULL,
  `amount` decimal(30,18) DEFAULT NULL,
  `payloadJson` longtext NOT NULL,
  `_snapshot_Id` int NOT NULL DEFAULT '0',
  `_account_Id` int DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `index_SnapshotItems_snapshot_type_key` (`_snapshot_Id`,`itemType`,`stableKey`),
  KEY `fk_SnapshotItems_account` (`_account_Id`),
  CONSTRAINT `fk_SnapshotItems_account` FOREIGN KEY (`_account_Id`) REFERENCES `accounts` (`Id`),
  CONSTRAINT `fk_SnapshotItems_snapshot` FOREIGN KEY (`_snapshot_Id`) REFERENCES `snapshots` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `accountbalances` AS select cast(row_number() OVER (ORDER BY `grouped`.`_account_Id`,`grouped`.`currency_type` )  as signed) AS `Id`,`grouped`.`amount` AS `amount`,`grouped`.`currency_type` AS `currency_type`,`grouped`.`_account_Id` AS `_account_Id` from (select `holdings`.`_account_Id` AS `_account_Id`,`holdings`.`_currentPrice_t` AS `currency_type`,sum((case when (`holdings`.`holdingType` = 'UST') then round((`holdings`.`quantity` * `holdings`.`_currentPrice_v`),2) else (`holdings`.`quantity` * `holdings`.`_currentPrice_v`) end)) AS `amount` from `holdings` group by `holdings`.`_account_Id`,`holdings`.`_currentPrice_t` having (`amount` <> 0)) `grouped`;

SET FOREIGN_KEY_CHECKS=1;
